#!/usr/bin/env bash

# Display "bad luck" for the 4th loop
# Display "good luck" for the 8th loop
# Display "Best School" for other iterations
# You must use while loop, if, elif, and else statements (for and until are forbidden)

count=0

while [ $count -lt 10 ]; do 
    if [ $count -eq 4 ]; then 
        echo "bad luck"
    elif [ $count -eq 8 ]; then 
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done

