#!/usr/bin/env bash

# Generate RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

# Check if the school file exists
if [ -f ~/.ssh/school ]; then
    echo "school file exists."
else
    echo "school file does not exist."
fi

